services:

  redis:
    image: redis
    ports:
      - 6379:6379
    restart: always
  
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=pass123
    networks:
      - nestjs-app

  adminer:
    image: adminer
    restart: always
    ports:
      - 8123:8080
    networks:
      - nestjs-app

networks:
  nestjs-app:
    driver: bridge

  # mongo:
  #   image: mongo
  #   restart: always
  #   ports:
  #     - 27017:27017
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: mongo
  #     MONGO_INITDB_ROOT_PASSWORD: mongo

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
  #     ME_CONFIG_MONGODB_URL: mongodb://mongo:mongo@mongo:27017/
  #     ME_CONFIG_BASICAUTH: false